services:
  app:
    build: ./app
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=password
      - DB_DATABASE=todo_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "80:5000"
  mysql:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -h 'localhost' -u 'root' -p'password' -e 'SELECT 1'",
        ]
      timeout: 20s
      retries: 10
      interval: 10s
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
    networks:
      - app-network
    ports:
      - 3306:3306
volumes:
  db-data:
networks:
  app-network:
